const enum Products {
  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE',
  FILTER_PRODUCTS = 'FILTER_PRODUCTS',
  FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS',
  FILTER_PRODUCTS_FAILURE = 'FILTER_PRODUCTS_FAILURE',
}
export default Products;
